# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2016-10-06 10:52
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Student',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('firstname', models.DateTimeField(auto_now_add=True)),
                ('lastname', models.CharField(blank=True, default=b'', max_length=100)),
                ('dept', models.TextField()),
                ('gender', models.BooleanField(default=False)),
                ('language', models.CharField(default=b'python', max_length=100)),
            ],
            options={
                'ordering': ('firstname',),
            },
        ),
    ]
