# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2016-10-06 11:15
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('basic_rest_app', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='student',
            name='firstname',
            field=models.CharField(blank=True, default=b'', max_length=100),
        ),
    ]
